name: mongodb-express

services:
  mongodb:
    image: mongodb:latest
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - mongodb-network
  
  mongodb-express:
    image: mongo-express:latest
    restart: always
    container_name: db-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - mongodb-network
    depends_on:
      - mongodb

networks:
  mongodb-network: